Ekart/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('common.urls')),
    path('customer/',include('customer.urls')),
    path('seller/',include('Seller.urls')),
    path('ekart_admin/',include('ekart_admin.urls')),
]

Seller/urls.py
from django.urls import path
from. import views

app_name = "Seller"

urlpatterns = [   
    path('',views.seller_home,name="seller_home"),
    path('add_product',views.add_product,name="add_product"),
    path('add_category',views.add_category,name="add_category"),
    path('view_product',views.view_products,name="view_product"),
    path('view_category',views.view_category,name="view_category"),
    path('profile',views.profile,name="profile"),
    path('view_orders',views.view_orders,name="view_orders"),

   
]

common/urls.py
from django.urls import path
from. import views

app_name = "common"

urlpatterns = [   
    path('',views.home, name='home'),  #path for home page
    path('seller_register',views.seller_register, name='seller_register'), 
    path('seller_login',views.seller_login, name='seller_login'), 
    path('customer_signup',views.customer_signup, name='customer_signup'), 
    path('customer_login',views.customer_login, name='customer_login'), 
    path('admin_login',views.admin_login, name='admin_login'), 

]

customer/urls.py
from django.urls import path
from. import views

app_name = "customer"

urlpatterns = [   
   path('customer_home',views.customer_home, name='customer_home'),
   path('store',views.store,name='store'),
   path('product_detail',views.product_detail,name='product_detail'),
   path('cart',views.cart,name='cart'),
   path('place_order',views.place_order,name='place_order'),
   path('order_complete',views.order_complete,name='order_complete'),
   path('dashboard',views.dashboard,name='dasboard')
   

]

ekart_admin/urls.py
from django.urls import path
from. import views

app_name = "ekart_admin"

urlpatterns = [   
   path('admin_home',views.admin_home,name="admin_home")
]

Seller/models.py
from django.db import models

# Create your models here.

common/models.py
from django.db import models

# Create your models here.

customer/models.py
from django.db import models

# Create your models here.

ekart_admin/models.py
from django.db import models

# Create your models here.

Seller/views.py
from django.shortcuts import render

# Create your views here.
def seller_home(request):
    return render(request, 'seller/seller_home.html')

def add_product(request):
    return render(request, 'seller/add_product.html')

def add_category(request):
    return render(request, 'seller/add_category.html')

def view_category(request):
    return render(request, 'seller/view_category.html')

def view_products(request):
    return render(request, 'seller/view_product.html')

def profile(request):
    return render(request,'seller/profile.html')

def view_orders(request):
    return render(request,'seller/view_orders.html')

common/views.py
from django.shortcuts import render

# Create your views here.


#functon for rendering home page
def home(request):
    return render(request,'common/home.html' )

#function for rendering seller register page
def seller_register(request):
    return render(request,'common/seller_register.html' )

#function for rendering seller login page
def seller_login(request):
    return render(request,'common/seller_login.html' )

#function for rendering customer register page
def customer_signup(request):
    return render(request,'common/customer_signup.html' )

#function for rendering customer login page
def customer_login(request):
    return render(request,'common/customer_login.html' )

def admin_login(request):
    return render(request,'common/admin_login.html' )

customer/views.py
from django.shortcuts import render

# Create your views here.


def customer_home(request):
    return render(request, 'customer/customer_home.html')


def store(request):
    return render(request, 'customer/store.html')


def product_detail(request):
    return render(request, 'customer/product_detail.html')


def cart(request):
    return render(request, 'customer/cart.html')


def place_order(request):
    return render(request, 'customer/place_order.html')


def order_complete(request):
    return render(request, 'customer/order_complete.html')


def dashboard(request):
    return render(request, 'customer/dashboard.html')

ekart_admin/views.py
from django.shortcuts import render

# Create your views here.
def admin_home(request):
    return render(request,'admin_home.html')

Seller/templates/seller/add_category.html
{% extends 'seller/base.html' %}
{% load static %}

{% block content %}


  
<main class="col-md-9">
    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">

        <!-- ============================ COMPONENT REGISTER   ================================= -->
        <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
            <article class="card-body">
                <header class="mb-4">
                    <h4 class="card-title">Add Category</h4>
                </header>
                <form action="" method="" enctype="multipart/form-data">
                    
                    <div class=" form-group">
                        <label>Category name</label>
                        <input type="text" class="form-control" name="category_name">
                    </div> <!-- form-group end.// -->
                    <div class="form-group">
                        <label>Description</label>
                        
                        <textarea name="description" id="" cols="30" rows="10"  class="form-control"></textarea>
                    </div> <!-- form-group end.// -->             

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Add Category </button>
                    </div> <!-- form-group// -->

                </form>
            </article><!-- card-body.// -->
        </div> <!-- card .// -->
        
        <br><br>
        <!-- ============================ COMPONENT REGISTER  END.// ================================= -->


    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->


</main>





{% endblock %}

Seller/templates/seller/includes/navbar.html
{% load static %}

<header class="section-header">
    <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTop4">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                 <a href="#" class="nav-link">   English </a>
                
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link"> USD </a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
            <li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
        </ul> <!-- list-inline //  -->
      </div> <!-- navbar-collapse .// -->
    </div> <!-- container //  -->
    </nav>
    
    <section class="header-main border-bottom">
        <div class="container">
    <div class="row align-items-center">
        <div class="col-lg-2 col-md-3 col-6">
            <a href="{% url 'customer:customer_home' %}" class="brand-wrap">
                <img class="logo" src="{% static './images/logo.png' %}">
            </a> <!-- brand-wrap.// -->
        </div>
        <div class="col-lg col-sm col-md col-6 flex-grow-0">
            <div class="category-wrap dropdown d-inline-block float-right">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> 
                    <i class="fa fa-bars"></i> All category 
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Machinery / Mechanical Parts / Tools </a>
                    <a class="dropdown-item" href="#">Consumer Electronics / Home Appliances </a>
                    <a class="dropdown-item" href="#">Auto / Transportation</a>
                    <a class="dropdown-item" href="#">Apparel / Textiles / Timepieces </a>
                    <a class="dropdown-item" href="#">Home & Garden / Construction / Lights </a>
                    <a class="dropdown-item" href="#">Beauty & Personal Care / Health </a> 
                </div>
            </div>  <!-- category-wrap.// -->
        </div> <!-- col.// -->
        <a href="{% url 'customer:store' %}" class="btn btn-outline-primary">Store</a>
        <div class="col-lg  col-md-6 col-sm-12 col">
            <form action="#" class="search">
                <div class="input-group w-100">
                    <input type="text" class="form-control" style="width:60%;" placeholder="Search">
                    
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="submit">
                        <i class="fa fa-search"></i>
                      </button>
                    </div>
                </div>
            </form> <!-- search-wrap .end// -->
        </div> <!-- col.// -->
        <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        <div class="widget-header">
                            <small class="title text-muted">Welcome guest!</small>
                            <div> 
                                <a href="">Log Out</a> <span class="dark-transp"> | </span>
                                
                            </div>
                        </div>
                        
                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
    </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->
    
    
    
    
    </header> <!-- section-header.// -->
    
    

Seller/templates/seller/includes/sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
        <a class="list-group-item active" href="{% url 'Seller:add_product' %}"> Add Products </a>
        <a class="list-group-item" href="{% url 'Seller:view_product' %}"> View Products </a>
        <a class="list-group-item" href="{% url 'Seller:add_category' %}"> Add category </a>
        <a class="list-group-item" href="{% url 'Seller:view_category' %}"> view Category </a>
        <a class="list-group-item" href="{% url 'Seller:profile' %}"> Profile </a>
        <a class="list-group-item" href="{% url 'Seller:view_orders' %}"> Received orders </a>
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="#"> <i class="fa fa-power-off"></i> <span class="text">Log
            out</span> </a>
    <!--   SIDEBAR .//END   -->
</aside>

Seller/templates/seller/profile.html
{% extends 'seller/base.html' %}
{% load static %}

{% block content %}


<main class="col-md-9">
   <h1>profile</h1>
</main>


{% endblock %}

Seller/templates/seller/view_category.html
{% extends 'seller/base.html' %}
{% load static %}

{% block content %}


<main class="col-md-9">
   <h1>view_category</h1>
</main>


{% endblock %}

Seller/templates/seller/view_orders.html
{% extends 'seller/base.html' %}
{% load static %}

{% block content %}


<main class="col-md-9">
   <h1>view_orders</h1>
</main>


{% endblock %}

Seller/templates/seller/view_product.html
{% extends 'seller/base.html' %}
{% load static %}

{% block content %}


<main class="col-md-9">
   <h1>view_products</h1>
</main>


{% endblock %}

common/templates/common/customer_login.html
{% extends 'common/base.html' %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
          <h4 class="card-title mb-4"> Admin Sign in</h4>
          <form>
              <div class="form-group">
                 <input type="email" class="form-control" placeholder="Email Address" >
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" class="form-control" placeholder="Password" >
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="#" class="float-right">Forgot password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <!-- <button type="submit" class="btn btn-primary btn-block"> Login  </button> -->
                  <a href="{% url 'ekart_admin:admin_home'%}" class="btn btn-primary btn-block"> Login  </a>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
        
      
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    
    

{% endblock%}

common/templates/common/home.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
<style>
    .info-wrap {
        text-align: center;       

    }
</style>


<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y-sm" style="padding-top: 100px;min-height: 500px;">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card card-product-grid">
                    <a href="{% url 'common:admin_login' %}" class="img-wrap"> <img src="{% static 'images/items/1.jpg' %}"> </a>
                    <figcaption class="info-wrap">
                        <a href="{% url 'common:admin_login' %}" class="title"><b>Admin</b></a>

                    </figcaption>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-4">
                <div class="card card-product-grid">
                    <a href="{% url 'common:seller_login' %}" class="img-wrap"> <img src="{% static 'images/items/2.jpg' %}"> </a>
                    <figcaption class="info-wrap">
                        <a href="{% url 'common:seller_login' %}" class="title"><b>Seller</b></a>

                    </figcaption>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-4">
                <div class="card card-product-grid">
                    <a href="{% url 'customer:customer_home' %}" class="img-wrap"> <img src="{% static 'images/items/3.jpg' %}"> </a>
                    <figcaption class="info-wrap">
                        <a href="{% url 'customer:customer_home' %}" class="title"><b>Customer</b> </a>

                    </figcaption>
                </div>

            </div> <!-- row.// -->

        </div><!-- container // -->
</section>
<!-- ========================= SECTION  END// ========================= -->



{% endblock %}

common/templates/common/seller_login.html
{% extends 'common/base.html' %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
          <h4 class="card-title mb-4">Seller Sign in</h4>
          <form>
              <div class="form-group">
                 <input type="email" class="form-control" placeholder="Email Address" >
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" class="form-control" placeholder="Password" >
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="#" class="float-right">Forgot password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <!-- <button type="submit" class="btn btn-primary btn-block"> Login  </button> -->
                  <a href="{% url 'Seller:seller_home' %}" class="btn btn-primary btn-block">Login</a>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url 'common:seller_register' %}">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    
    

{% endblock%}

customer/templates/customer/cart.html
{% extends 'customer/base.html' %}
{% load static %}

{% block content %}
<section class="section-content padding-y bg">
    <div class="container">

        <!-- ============================ COMPONENT 1 ================================= -->

        <div class="row">
            <aside class="col-lg-9">
                <div class="card">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right" width="200"> </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{% static './images/items/11.jpg' %}" class="img-sm"></div>
                                        <figcaption class="info">
                                            <a href="#" class="title text-dark">Camera Canon EOS M50 Kit</a>
                                            <p class="text-muted small">Matrix: 25 Mpx <br> Brand: Canon</p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <!-- col.// -->
                                    <div class="col">
                                        <div class="input-group input-spinner">
                                            <div class="input-group-prepend">
                                                <button class="btn btn-light" type="button" id="button-plus"> <i
                                                        class="fa fa-minus"></i> </button>
                                            </div>
                                            <input type="text" class="form-control" value="1">
                                            <div class="input-group-append">
                                                <button class="btn btn-light" type="button" id="button-minus"> <i
                                                        class="fa fa-plus"></i> </button>
                                            </div>
                                        </div> <!-- input-group.// -->
                                    </div> <!-- col.// -->
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">$1156.00</var>
                                        <small class="text-muted"> $315.20 each </small>
                                    </div> <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <a href="" class="btn btn-danger"> Remove</a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{% static './images/items/10.jpg' %}" class="img-sm"></div>
                                        <figcaption class="info">
                                            <a href="#" class="title text-dark">ADATA Premier ONE microSDXC</a>
                                            <p class="text-muted small">Size: 256 GB <br> Brand: ADATA </p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <!-- col.// -->
                                    <div class="col">
                                        <div class="input-group input-spinner">
                                            <div class="input-group-prepend">
                                                <button class="btn btn-light" type="button" id="button-plus"> <i
                                                        class="fa fa-minus"></i> </button>
                                            </div>
                                            <input type="text" class="form-control" value="1">
                                            <div class="input-group-append">
                                                <button class="btn btn-light" type="button" id="button-minus"> <i
                                                        class="fa fa-plus"></i> </button>
                                            </div>
                                        </div> <!-- input-group.// -->
                                    </div> <!-- col.// -->
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">$149.97</var>
                                        <small class="text-muted"> $75.00 each </small>
                                    </div> <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <a href="" class="btn btn-danger"> Remove</a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{% static './images/items/9.jpg' %}" class="img-sm"></div>
                                        <figcaption class="info">
                                            <a href="#" class="title text-dark">Logitec headset for gaming</a>
                                            <p class="small text-muted">Version: CUH-ZCT2E <br> Brand: Sony</p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <!-- col.// -->
                                    <div class="col">
                                        <div class="input-group input-spinner">
                                            <div class="input-group-prepend">
                                                <button class="btn btn-light" type="button" id="button-plus"> <i
                                                        class="fa fa-minus"></i> </button>
                                            </div>
                                            <input type="text" class="form-control" value="1">
                                            <div class="input-group-append">
                                                <button class="btn btn-light" type="button" id="button-minus"> <i
                                                        class="fa fa-plus"></i> </button>
                                            </div>
                                        </div> <!-- input-group.// -->
                                    </div> <!-- col.// -->
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">$98.00</var>
                                        <small class="text-muted"> $578.00 each</small>
                                    </div> <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <a href="" class="btn btn-danger"> Remove</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div> <!-- card.// -->

            </aside> <!-- col.// -->
            <aside class="col-lg-3">

                <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                            <dt>Total price:</dt>
                            <dd class="text-right">$69.97</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Tax:</dt>
                            <dd class="text-right"> $10.00</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Total:</dt>
                            <dd class="text-right text-dark b"><strong>$59.97</strong></dd>
                        </dl>
                        <hr>
                        <p class="text-center mb-3">
                            <img src="{% static './images/misc/payments.png' %}" height="26">
                        </p>
                        <a href="{% url 'customer:place_order' %}" class="btn btn-primary btn-block"> Checkout </a>
                        <a href="{% url 'customer:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                    </div> <!-- card-body.// -->
                </div> <!-- card.// -->

            </aside> <!-- col.// -->


        </div> <!-- row.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->

    </div> <!-- container .//  -->
</section>
<!-- ==============

{% endblock %}

customer/templates/customer/includes/navbar.html
{% load static %}

<header class="section-header">
    <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTop4">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                 <a href="#" class="nav-link">   English </a>
                
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link"> USD </a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
            <li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
        </ul> <!-- list-inline //  -->
      </div> <!-- navbar-collapse .// -->
    </div> <!-- container //  -->
    </nav>
    
    <section class="header-main border-bottom">
        <div class="container">
    <div class="row align-items-center">
        <div class="col-lg-2 col-md-3 col-6">
            <a href="{% url 'customer:customer_home' %}" class="brand-wrap">
                <img class="logo" src="{% static './images/logo.png' %}">
            </a> <!-- brand-wrap.// -->
        </div>
        <div class="col-lg col-sm col-md col-6 flex-grow-0">
            <div class="category-wrap dropdown d-inline-block float-right">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> 
                    <i class="fa fa-bars"></i> All category 
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Machinery / Mechanical Parts / Tools </a>
                    <a class="dropdown-item" href="#">Consumer Electronics / Home Appliances </a>
                    <a class="dropdown-item" href="#">Auto / Transportation</a>
                    <a class="dropdown-item" href="#">Apparel / Textiles / Timepieces </a>
                    <a class="dropdown-item" href="#">Home & Garden / Construction / Lights </a>
                    <a class="dropdown-item" href="#">Beauty & Personal Care / Health </a> 
                </div>
            </div>  <!-- category-wrap.// -->
        </div> <!-- col.// -->
        <a href="{% url 'customer:store' %}" class="btn btn-outline-primary">Store</a>
        <div class="col-lg  col-md-6 col-sm-12 col">
            <form action="#" class="search">
                <div class="input-group w-100">
                    <input type="text" class="form-control" style="width:60%;" placeholder="Search">
                    
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="submit">
                        <i class="fa fa-search"></i>
                      </button>
                    </div>
                </div>
            </form> <!-- search-wrap .end// -->
        </div> <!-- col.// -->
        <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        <div class="widget-header">
                            <small class="title text-muted">Welcome guest!</small>
                            <div> 
                                <a href="{% url 'common:customer_login' %}">Sign in</a> <span class="dark-transp"> | </span>
                                <a href="{% url 'common:customer_signup' %}"> Register</a>
                            </div>
                        </div>
                        <a href="{% url 'customer:cart' %}" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                            <span class="badge badge-pill badge-danger notify">0</span>
                        </a>
                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
    </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->
    
    
    
    
    </header> <!-- section-header.// -->
    
    